version: '3.6'

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

networks:
  replication_network:
    driver: bridge

services:
  auth_service:
    build: ./apps/keycloak
    container_name: auth_service
    volumes:
      - './apps/keycloak/themes:/opt/keycloak/themes/my-theme'
    environment:
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HOSTNAME: ${KC_HOSTNAME}
      PROXY_ADDRESS_FORWARDING: true

      GF_URL: ${GF_HOSTNAME}:${GF_SERVER_HTTP_PORT}
      GF_ADMIN_USERNAME: ${GF_ADMIN_USERNAME}
      GF_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
    logging: *logging
    networks:
      replication_network:

    # command: -v start --optimized
    command: ["start-dev", "--import-realm"]
    depends_on:
      - postgres
    ports:
      # http
      - 8080:8080
      # https
      - 8443:8443
      # healthckeck
      - 9000:9000

  postgres:
    image: postgres:16.3
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      replication_network:

  # nestjs as backend
  # debug mode is not working between docker and nx, checkout this in the feature.
  # issue: https://github.com/nrwl/nx/issues/14126
  # nestjs:
  #   extends:
  #     file: compose.base.yaml
  #     service: nx-app-base
  #   command: npm run start:b
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./apps/backend
  #         target: /app/apps/backend
  #         ignore:
  #           - node_modules/
  #       - action: rebuild
  #         path: ./package.json
  #         target: /app/package.json
  #       - action: sync+restart
  #         path: ./apps/backend/webpack.config.js
  #         target: /app/apps/backend/webpack.config.js

  # angular as frontend
  # angular:
  #   extends:
  #     file: compose.base.yaml
  #     service: nx-app-base
  #   command: npm run start:f
  #   ports:
  #     - 4200:4200
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./apps/frontend
  #         target: /app/apps/frontend
  #         ignore:
  #           - node_modules/
  #       - action: rebuild
  #         path: ./package.json
  #         target: /app/package.json

volumes:
  postgres_data:
    driver: local



