version: '3.6'

services:
  nx-app-base:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
    # volumes: (use docker-compose watch instead
      # - ./:/app
      # - mono-node-modules:/app/node_modules
      # - mono-nx-cache:/app/.nx
